In [ ]:
import pandas as pd

# дано:
cats = [('Мартин', 5, 'Алексей', 'Егоров'),
    	('Фродо', 3, 'Анна', 'Самохина'),
    	('Вася', 4, 'Андрей', 'Белов'),
    	('Муся', 7, 'Игорь', 'Бероев'),
    	('Изольда', 2, 'Игорь', 'Бероев'),
    	('Снейп', 1, 'Марина', 'Апраксина'),
    	('Лютик', 4, 'Виталий', 'Соломин'),
    	('Снежок', 3, 'Марина', 'Апраксина'),
    	('Марта', 5, 'Сергей', 'Колесников'),
    	('Буся', 12, 'Алена', 'Федорова'),
    	('Джонни', 10, 'Игорь', 'Андропов'),
    	('Мурзик', 1,'Даниил', 'Невзоров'),
    	('Барсик', 2, 'Виталий', 'Соломин'),
    	('Рыжик', 7, 'Владимир', 'Медведев'),
        ('Матильда', 8, 'Андрей', 'Белов'),
    	('Гарфилд', 3, 'Александр', 'Березуев')]

Найти: 1)Самого молодого питомца
2)Самого старого питомца
3)Внести данные еще об одном питомце
4)Вывести на экран всех владельцев с определенным именем и клички их животных
5)Вычислить средний возраст питомцев

##### DataFrame - это двумерный набор данных (в виде таблички)

In [ ]:
columns = ['Кличка питомца', 'Возраст питомца', 'Имя владельца', 'Фамилия владельца']

data_base = pd.DataFrame(cats, columns=columns)
data_base.head()  # визуализация первых 5 значений

  Кличка питомца  Возраст питомца Имя владельца Фамилия владельца
0         Мартин                5       Алексей            Егоров
1          Фродо                3          Анна          Самохина
2           Вася                4        Андрей             Белов
3           Муся                7         Игорь            Бероев
4        Изольда                2         Игорь            Бероев

In [26]:
# 1) Самый молодой питомец
age_pet = data_base["Возраст питомца"]
columns1 = ["Кличка питомца", "Возраст питомца"]

youngest_pet = data_base.loc[age_pet == age_pet.min(), columns1]
# атрибут .loc - это индексация по названию колонок

youngest_pet

   Кличка питомца  Возраст питомца
5           Снейп                1
11         Мурзик                1

In [28]:
# 2) Самый старый питомец

oldest_pet = data_base.loc[age_pet == age_pet.max(), columns1]

oldest_pet

  Кличка питомца  Возраст питомца
9           Буся               12

In [ ]:
# 3) Внести данные ещё об одном питомце
tuple_pet = ("Кузя", 4, "Дмитрий", "Cмирнов")

pet_df = pd.DataFrame([tuple_pet], columns=data_base.columns)

frames = [data_base, pet_df]

update_data_base = pd.concat(frames, ignore_index=True)
# .concate - это конкантенация табличек в пандасе

update_data_base

   Кличка питомца  Возраст питомца Имя владельца Фамилия владельца
0          Мартин                5       Алексей            Егоров
1           Фродо                3          Анна          Самохина
2            Вася                4        Андрей             Белов
3            Муся                7         Игорь            Бероев
4         Изольда                2         Игорь            Бероев
5           Снейп                1        Марина         Апраксина
6           Лютик                4       Виталий           Соломин
7          Снежок                3        Марина         Апраксина
8           Марта                5        Сергей        Колесников
9            Буся               12         Алена          Федорова
10         Джонни               10         Игорь          Андропов
11         Мурзик                1        Даниил          Невзоров
12         Барсик                2       Виталий           Соломин
13          Рыжик                7      Владимир          Медведев
14       Матильда                8        Андрей             Белов
15        Гарфилд                3     Александр          Березуев
16           Кузя                4       Дмитрий           Cмирнов

In [ ]:
# 5) вывести на экран владельцев с определённым именем и клички их питомцев
# пусть будет имя владельца: 'Даниил'

specific_name = update_data_base.loc[update_data_base["Имя владельца"] == "Даниил", ["Кличка питомца", "Имя владельца"]]

specific_name

   Кличка питомца Имя владельца
11         Мурзик        Даниил

In [ ]:
# вычислить средний возраст питомцев

update_data_base.describe()  
# функция .describe() позволяет посмотреть основные характеристики датафрейма (работает только с числовыми типами данных)
# Средний это строка mean

       Возраст питомца
count        17.000000
mean          4.764706
std           3.113065
min           1.000000
25%           3.000000
50%           4.000000
75%           7.000000
max          12.000000